version: 2
updates:
- package-ecosystem: pip
  directory: "/config"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django-colorfield
    versions:
    - "> 0.2.1"
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: pylint
    versions:
    - 2.6.0
    - 2.7.0
    - 2.7.2
    - 2.7.4
  - dependency-name: ipython
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
  - dependency-name: openpyxl
    versions:
    - 3.0.6
  - dependency-name: django-simple-history
    versions:
    - 2.12.0
  - dependency-name: drf-firebase-auth
    versions:
    - 0.0.8
