language: python

sudo: required

git:
  depth: false
  quiet: true

python:
  - '3.6'

services:
  - docker

install:
  - mv django.env.sample django.env
  - mv postgres.env.sample postgres.env
  - mv mbtiles.env.sample mbtiles.env
  - touch auth.env
  - make pull-images
  - 'if ! make check-python-image; then make python-image; fi'
  - make image
  - docker-compose build

jobs:
  include:
    - stage: tests
      script:
        - docker-compose run --entrypoint black web . --exclude /migrations/ --diff --check
        - docker-compose run --entrypoint pylint web --ignore=tests ./api/
        - docker-compose run --entrypoint pylint web --rcfile=api/tests/pylintrc ./api/tests
        - docker-compose run --entrypoint sh -e ENV=dev -e CLIENT_API_KEY web init.sh
          python manage.py test --debug-mode
    - stage: docker push
      if: branch = staging AND type = push
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make push-python
        - make push-image

branches:
  only:
    - staging
    - trying

before_install:
  - openssl aes-256-cbc -K $encrypted_14955f54f703_key -iv $encrypted_14955f54f703_iv
    -in firebase.json.enc -out config/firebase.json -d
