language: python

sudo: required

python:
  - "3.6"

services:
  - docker

install:
  - mv django.env.sample django.env
  - mv postgres.env.sample postgres.env
  - docker-compose build

script:
  - docker-compose run web black . --exclude /migrations/ --diff --check
  - echo "Testing skipped for now"
#  - docker-compose run --service-ports web ash init.sh python -m coverage run --source=APP manage.py test
