FROM deniscarriere/mbtiles-server

LABEL maintainer="Mikhail Orlov <miklergm@gmail.com>"

RUN apk update \
  && apk add --virtual build-dependencies \
  build-base \
  gcc \
  sqlite-dev \
  zlib-dev \
  git \
  && apk add \
  bash

WORKDIR /opt

RUN git clone --depth 1 https://github.com/mapbox/tippecanoe.git tippecanoe-src

WORKDIR /opt/tippecanoe-src
# failed to make with LDFLAGS=-static 
RUN make \
  && PREFIX=/opt/tippecanoe make install


FROM deniscarriere/mbtiles-server



COPY --from=0 /opt/tippecanoe/bin/* /usr/bin/

RUN apk add --no-cache libgcc libstdc++ sqlite-libs


RUN mkdir -p /root/mbtiles

# Enables customized options using environment variables
ENV ZOOM='8'
ENV MBTILES_SERVER_CACHE='/root/mbtiles'
ENV MBTILES_SERVER_PROTOCOL='http'
ENV MBTILES_SERVER_DOMAIN='localhost'
ENV MBTILES_SERVER_PORT='5000'
ENV MBTILES_SERVER_VERBOSE='true'

