version: '3'
services:
  db:
    image: mdillon/postgis:10-alpine
    container_name: postgres01
    ports:
      - '5432'
    env_file:
      - postgres.env
  nginx:
    image: nginx:1.13-alpine
    container_name: nginx01
    ports:
      - '80:80'
    volumes:
      - ./project:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: django01
    depends_on:
      - db
    volumes:
      - ./project:/src
    expose:
      - '80'
    ports:
      - '3500:3500'
      - '8006:81'
    env_file:
      - django.env
    restart: always
