FROM mhart/alpine-node:8
# deniscarriere/mbtiles-server
# Failed with apline-node:10

LABEL maintainer="Mikhail Orlov <miklergm@gmail.com>"

RUN apk update \
  && apk add --virtual build-dependencies \
    build-base \
    gcc \
    sqlite-dev \
    zlib-dev \
    git \
  && apk add \
    bash

RUN mkdir -p /src
WORKDIR /src

RUN git clone https://github.com/mapbox/tippecanoe.git tippecanoe
RUN git clone https://github.com/DenisCarriere/mbtiles-server.git mbtiles

WORKDIR ./tippecanoe
RUN make \
  && make install

# RUN make test

WORKDIR ../mbtiles
RUN yarn

RUN mkdir -p /root/mbtiles

# Enables customized options using environment variables
ENV ZOOM='8'
ENV CACHE='/root/mbtiles'
ENV PROTOCOL='http'
ENV DOMAIN='localhost'
ENV PORT='5000'
ENV VERBOSE='true'

# Run App
EXPOSE 5000
CMD ["yarn", "start"]