version: '3'
services:
  db:
    image: mdillon/postgis:10-alpine
    ports:
      - '5432'
    env_file:
      - postgres.env
    volumes:
    - ./data:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:1.13-alpine
    ports:
      - '3080:80'
    volumes:
      - ./project:/src
      - ./config/nginx/allowed_ips.conf:/etc/nginx/allowed_ips.conf
      - ./config/nginx.${ENV:-dev}:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./project:/src
    expose:
      - '80'
    ports:
      - '8006:81'
    env_file:
      - django.env
      - postgres.env
    restart: always
