FROM mhart/alpine-node:8
# deniscarriere/mbtiles-server
# Failed with apline-node:10

LABEL maintainer="Mikhail Orlov <miklergm@gmail.com>"

RUN apk update \
  && apk add --virtual build-dependencies \
  build-base \
  gcc \
  sqlite-dev \
  zlib-dev \
  git \
  && apk add \
  bash

WORKDIR /opt

RUN git clone --depth 1 https://github.com/mapbox/tippecanoe.git tippecanoe-src
RUN git clone --depth 1 https://github.com/DenisCarriere/mbtiles-server.git mbtiles

WORKDIR /opt/tippecanoe-src
# failed to make with LDFLAGS=-static 
RUN make \
  && PREFIX=/opt/tippecanoe make install


FROM mhart/alpine-node:8

COPY --from=0 /opt/tippecanoe/bin/* /usr/bin/
COPY --from=0 /opt/mbtiles/ /opt/mbtiles

COPY --from=0 /lib/ld-musl* /lib/
COPY --from=0 /lib/libz.so* /lib/
COPY --from=0 /usr/lib/libsqlite3* /usr/lib/
COPY --from=0 /usr/lib/libstdc++.so* /usr/lib/
COPY --from=0 /usr/lib/libgcc_s.so* /usr/lib/
COPY --from=0 /lib/ld-musl-x86_64.so* /lib/

WORKDIR /opt/mbtiles
RUN yarn

RUN mkdir -p /root/mbtiles

# Enables customized options using environment variables
ENV ZOOM='8'
ENV CACHE='/root/mbtiles'
ENV PROTOCOL='http'
ENV DOMAIN='localhost'
ENV PORT='5000'
ENV VERBOSE='true'

# Run App
EXPOSE 5000
CMD ["yarn", "start"]
