version: "3"
services:
  db:
    image: postgis/postgis:12-3.0-alpine
    ports:
      - "5432"
    env_file:
      - postgres.env
      - mbtiles.env
    volumes:
      - ./data/initdb:/docker-entrypoint-initdb.d
      - ./data/db:/var/lib/postgresql/data
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./project:/src
    depends_on:
      - web
  web:
    image: chronmaps/backend:latest
    depends_on:
      - db
    volumes:
      - ./project:/src
      - ./config:/config
    ports:
      - "8086:80"
      - "8006:81"
    env_file:
      - django.env
      - postgres.env
      - auth.env
  redis:
    image: redis:alpine
  mbtiles:
    image: morlov/mbtiles-psql:latest
    env_file:
      - mbtiles.env
      - postgres.env
    ports:
      - "5000:5000"
    volumes:
      - ./data/mbtiles:/root/mbtiles
      - ./data/scripts:/scripts
      - ./data/data:/data