version: '3'
services:
  db:
    ports:
      - '25432:5432'
  web:
    environment:
      - ENV=dev
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "25555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
