FROM chronmaps/backend:deps-build as build

LABEL maintainer="Mikhail Orlov <miklergm@gmail.com>"

COPY /config/requirements.txt /
RUN pip install -r /requirements.txt --user --upgrade

FROM chronmaps/backend:deps-base as base

COPY --from=build /opt/python /opt/python/
COPY /config/requirements.txt /

ENTRYPOINT /bin/sh
