# Generated by Django 2.1.2 on 2018-11-27 06:00

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('control_type', models.PositiveIntegerField(choices=[(0, 'direct'), (1, 'indirect'), (2, 'group')])),
                ('control_degree', models.PositiveIntegerField(blank=True, choices=[(15239622, 'disputed'), (44107133, 'occupied')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerritorialEntity',
            fields=[
                ('wikidata_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('color', colorfield.fields.ColorField(max_length=18)),
                ('admin_level', models.PositiveIntegerField()),
                ('predecessors', models.ManyToManyField(blank=True, related_name='_territorialentity_predecessors_+', to='api.TerritorialEntity')),
            ],
        ),
        migrations.AddField(
            model_name='politicalrelation',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='politicalrelation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.TerritorialEntity'),
        ),
    ]
