# Generated by Django 2.1.2 on 2018-11-29 01:55

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPoliticalRelation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('control_type', models.PositiveIntegerField(choices=[(10, 'direct'), (11, 'direct_occupied'), (12, 'direct_disputed'), (20, 'indirect'), (21, 'indirect_disputed'), (30, 'group')])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical political relation',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTerritorialEntity',
            fields=[
                ('wikidata_id', models.PositiveIntegerField(db_index=True)),
                ('color', colorfield.fields.ColorField(max_length=18)),
                ('admin_level', models.PositiveIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical territorial entity',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PoliticalRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('control_type', models.PositiveIntegerField(choices=[(10, 'direct'), (11, 'direct_occupied'), (12, 'direct_disputed'), (20, 'indirect'), (21, 'indirect_disputed'), (30, 'group')])),
            ],
        ),
        migrations.CreateModel(
            name='TerritorialEntity',
            fields=[
                ('wikidata_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('color', colorfield.fields.ColorField(max_length=18)),
                ('admin_level', models.PositiveIntegerField()),
                ('predecessors', models.ManyToManyField(blank=True, related_name='_territorialentity_predecessors_+', to='api.TerritorialEntity')),
                ('relations', models.ManyToManyField(blank=True, related_name='political_relations', through='api.PoliticalRelation', to='api.TerritorialEntity')),
            ],
        ),
        migrations.AddField(
            model_name='politicalrelation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='api.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='politicalrelation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='historicalpoliticalrelation',
            name='child',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='historicalpoliticalrelation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpoliticalrelation',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.TerritorialEntity'),
        ),
    ]
