# Generated by Django 2.1.2 on 2018-12-20 10:13

import colorfield.fields
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtomicPolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.TextField(max_length=100, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAtomicPolygon',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('wikidata_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.TextField(db_index=True, max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical atomic polygon',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPoliticalRelation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('control_type', models.PositiveIntegerField(choices=[(10, 'direct'), (11, 'direct_occupied'), (12, 'direct_disputed'), (20, 'indirect'), (21, 'indirect_disputed'), (30, 'group')])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical political relation',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSpacetimeVolume',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), size=None)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical spacetime volume',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTerritorialEntity',
            fields=[
                ('wikidata_id', models.PositiveIntegerField(db_index=True)),
                ('color', colorfield.fields.ColorField(max_length=18)),
                ('admin_level', models.PositiveIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical territorial entity',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MapSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('zoom_min', models.IntegerField()),
                ('zoom_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Narration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('date_label', models.CharField(max_length=100)),
                ('map_datetime', models.DateTimeField()),
                ('img', models.URLField()),
                ('video', models.URLField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Narrative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('control_type', models.PositiveIntegerField(choices=[(10, 'direct'), (11, 'direct_occupied'), (12, 'direct_disputed'), (20, 'indirect'), (21, 'indirect_disputed'), (30, 'group')])),
            ],
        ),
        migrations.CreateModel(
            name='SpacetimeVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='TerritorialEntity',
            fields=[
                ('wikidata_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('color', colorfield.fields.ColorField(max_length=18)),
                ('admin_level', models.PositiveIntegerField()),
                ('predecessors', models.ManyToManyField(blank=True, related_name='_territorialentity_predecessors_+', to='api.TerritorialEntity')),
                ('relations', models.ManyToManyField(blank=True, related_name='political_relations', through='api.PoliticalRelation', to='api.TerritorialEntity')),
            ],
        ),
        migrations.AddField(
            model_name='spacetimevolume',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='spacetimevolume',
            name='territory',
            field=models.ManyToManyField(to='api.AtomicPolygon'),
        ),
        migrations.AddField(
            model_name='politicalrelation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='api.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='politicalrelation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='narration',
            name='narrative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Narrative'),
        ),
        migrations.AddField(
            model_name='narration',
            name='settings_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MapSettings'),
        ),
        migrations.AddField(
            model_name='historicalspacetimevolume',
            name='entity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='historicalspacetimevolume',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpoliticalrelation',
            name='child',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='historicalpoliticalrelation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpoliticalrelation',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.TerritorialEntity'),
        ),
    ]
