# Generated by Django 2.1.2 on 2018-12-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narration',
            name='img',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='narration',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
