# Generated by Django 2.1.2 on 2018-11-19 02:15

import api.ltree
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directpoliticalrelation',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.DirectPoliticalRelation'),
        ),
        migrations.AddField(
            model_name='directpoliticalrelation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='indirectpoliticalrelation',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.IndirectPoliticalRelation'),
        ),
        migrations.AddField(
            model_name='indirectpoliticalrelation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='politicalentity',
            name='predecessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.PoliticalEntity'),
        ),
    ]
