# Generated by Django 2.1.2 on 2018-12-01 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_atomicpolygon_historicalatomicpolygon_historicalspacetimevolume_spacetimevolume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacetimevolume',
            name='territory',
        ),
        migrations.AddField(
            model_name='atomicpolygon',
            name='st',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territories', to='api.SpacetimeVolume'),
        ),
        migrations.AddField(
            model_name='historicalatomicpolygon',
            name='st',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.SpacetimeVolume'),
        ),
    ]
