# Generated by Django 2.1.2 on 2018-12-02 19:24

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_atomicpolygon_historicalatomicpolygon_historicalspacetimevolume_spacetimevolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryLevelLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('country', models.PositiveIntegerField()),
                ('disputed', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('color', models.PositiveIntegerField()),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('related_events', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='GroupLevelLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('areas', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('color', models.PositiveIntegerField()),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('related_events', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='IndependentLevelLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('area', models.PositiveIntegerField()),
                ('color', models.PositiveIntegerField()),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('related_events', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RegionalLevelLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('country', models.PositiveIntegerField()),
                ('region', models.PositiveIntegerField()),
                ('color', models.PositiveIntegerField()),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('related_events', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
            ],
        ),
    ]
