# Generated by Django 2.1.2 on 2018-12-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181220_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narration',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='narration',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
