# Generated by Django 2.1.5 on 2019-02-10 21:19

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190210_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspacetimevolume',
            name='visual_center',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spacetimevolume',
            name='visual_center',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
            preserve_default=False,
        ),
    ]
