# Generated by Django 2.1.2 on 2018-12-17 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_atomicpolygon_historicalatomicpolygon_historicalspacetimevolume_spacetimevolume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atomicpolygon',
            name='children',
        ),
        migrations.RemoveField(
            model_name='atomicpolygon',
            name='live',
        ),
        migrations.RemoveField(
            model_name='historicalatomicpolygon',
            name='live',
        ),
    ]
