# Generated by Django 2.1.2 on 2018-12-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_atomicpolygon_historicalatomicpolygon_historicalspacetimevolume_spacetimevolume'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicpolygon',
            name='live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalatomicpolygon',
            name='live',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='atomicpolygon',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='api.AtomicPolygon'),
        ),
    ]
