# Generated by Django 2.1.2 on 2018-12-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181220_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narration',
            old_name='settings_id',
            new_name='settings',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='language',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='narration',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='title',
            field=models.TextField(),
        ),
    ]
