# Generated by Django 2.1.2 on 2018-12-04 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_countrylevellayer_grouplevellayer_independentlevellayer_regionallevellayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrylevellayer',
            old_name='sources',
            new_name='references',
        ),
        migrations.RenameField(
            model_name='grouplevellayer',
            old_name='sources',
            new_name='references',
        ),
        migrations.RenameField(
            model_name='independentlevellayer',
            old_name='sources',
            new_name='references',
        ),
        migrations.RenameField(
            model_name='regionallevellayer',
            old_name='sources',
            new_name='references',
        ),
    ]
