# Generated by Django 2.1.2 on 2018-12-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181224_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsettings',
            name='zoom_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='zoom_min',
            field=models.FloatField(),
        ),
    ]
