# Generated by Django 2.1.2 on 2018-12-05 19:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181204_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrylevellayer',
            name='references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), size=None),
        ),
    ]
