# Generated by Django 2.1.7 on 2019-03-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190220_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpoliticalrelation',
            name='user_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politicalrelation',
            name='user_created',
            field=models.BooleanField(default=False),
        ),
    ]
