# Generated by Django 2.1.2 on 2018-11-19 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_indirectpoliticalrelation_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directpoliticalrelation',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='indirectpoliticalrelation',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='politicalentity',
            name='predecessor',
        ),
        migrations.AddField(
            model_name='directpoliticalrelation',
            name='entity',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.PoliticalEntity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indirectpoliticalrelation',
            name='entity',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.PoliticalEntity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politicalentity',
            name='predecessors',
            field=models.ManyToManyField(blank=True, related_name='_politicalentity_predecessors_+', to='api.PoliticalEntity'),
        ),
        migrations.AlterField(
            model_name='directpoliticalrelation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.DirectPoliticalRelation'),
        ),
        migrations.AlterField(
            model_name='indirectpoliticalrelation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.IndirectPoliticalRelation'),
        ),
        migrations.AlterField(
            model_name='politicalentity',
            name='wikidata_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='directpoliticalrelation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='indirectpoliticalrelation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='directpoliticalrelation',
            name='child_entity',
        ),
        migrations.RemoveField(
            model_name='directpoliticalrelation',
            name='parent_entity',
        ),
        migrations.RemoveField(
            model_name='indirectpoliticalrelation',
            name='child_entity',
        ),
        migrations.RemoveField(
            model_name='indirectpoliticalrelation',
            name='parent_entity',
        ),
    ]
