# Generated by Django 2.2 on 2019-04-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190325_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmapsettings',
            name='bbox',
        ),
        migrations.RemoveField(
            model_name='mapsettings',
            name='bbox',
        ),
    ]
