# Generated by Django 2.1.4 on 2019-01-14 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181230_1918'),
        ('api', '0005_auto_20181230_1155'),
    ]

    operations = [
    ]
