# Generated by Django 2.1.7 on 2019-03-28 03:43

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190325_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheddata',
            name='date',
            field=api.fields.JDNField(),
        ),
        migrations.AlterField(
            model_name='historicalcacheddata',
            name='date',
            field=api.fields.JDNField(),
        ),
    ]
