# Generated by Django 2.1.2 on 2018-12-05 19:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181205_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrylevellayer',
            name='disputed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='countrylevellayer',
            name='related_events',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
    ]
