# Generated by Django 2.1.7 on 2019-04-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0006_auto_20190416_1006")]

    operations = [
        migrations.AddField(
            model_name="cacheddata",
            name="date",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="city",
            name="dissolution_date",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="inception_date",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcacheddata",
            name="date",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcity",
            name="dissolution_date",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalcity",
            name="inception_date",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalnarration",
            name="map_datetime",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalpoliticalrelation",
            name="end_date",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalpoliticalrelation",
            name="start_date",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalspacetimevolume",
            name="end_date",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalspacetimevolume",
            name="start_date",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="narration",
            name="map_datetime",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="politicalrelation",
            name="end_date",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="politicalrelation",
            name="start_date",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spacetimevolume",
            name="end_date",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spacetimevolume",
            name="start_date",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
