# Generated by Django 2.1.2 on 2018-12-05 22:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181205_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpoliticalrelation',
            name='references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), default=['ref'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politicalrelation',
            name='references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), default=['ref'], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grouplevellayer',
            name='references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), size=None),
        ),
    ]
