# Generated by Django 2.1.5 on 2019-01-17 18:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20190114_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_id', models.PositiveIntegerField()),
                ('label', models.TextField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('inception_date', models.DateField()),
                ('dissolution_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
