# Generated by Django 2.1.5 on 2019-01-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpoliticalrelation',
            name='control_type',
            field=models.PositiveIntegerField(choices=[(10, 'direct'), (20, 'indirect'), (30, 'group')]),
        ),
        migrations.AlterField(
            model_name='politicalrelation',
            name='control_type',
            field=models.PositiveIntegerField(choices=[(10, 'direct'), (20, 'indirect'), (30, 'group')]),
        ),
        migrations.AlterField(
            model_name='spacetimevolume',
            name='territory',
            field=models.ManyToManyField(related_name='stvs', to='api.AtomicPolygon'),
        ),
    ]
