# Generated by Django 2.1.7 on 2019-04-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile'),
        ('api', '0007_auto_20190418_1009'),
    ]

    operations = [
    ]
