# Generated by Django 2.1.2 on 2018-11-22 01:36

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_api_ltree_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirectpoliticalrelation',
            name='relation_type',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='politicalentity',
            name='admin_level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='politicalentity',
            name='color',
            field=colorfield.fields.ColorField(max_length=18),
        ),
        migrations.AlterField(
            model_name='politicalentity',
            name='wikidata_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
