# Generated by Django 2.1.5 on 2019-01-31 17:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspacetimevolume',
            name='visual_center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='spacetimevolume',
            name='visual_center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='historicalpoliticalrelation',
            name='control_type',
            field=models.PositiveIntegerField(choices=[(10, 'direct'), (20, 'indirect'), (30, 'group')]),
        ),
        migrations.AlterField(
            model_name='politicalrelation',
            name='control_type',
            field=models.PositiveIntegerField(choices=[(10, 'direct'), (20, 'indirect'), (30, 'group')]),
        ),
    ]
