# Generated by Django 2.1.5 on 2019-01-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tilebbox'),
        ('api', '0007_city'),
    ]

    operations = [
    ]
