# Generated by Django 2.1.5 on 2019-02-07 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190129_1408'),
        ('api', '0008_auto_20190131_1706'),
    ]

    operations = [
    ]
