# Generated by Django 2.1.5 on 2019-02-07 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20190120_1751'),
        ('api', '0008_auto_20190129_1408'),
    ]

    operations = [
    ]
