# Generated by Django 2.2 on 2019-04-21 04:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190419_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalatomicpolygon',
            name='history_user',
        ),
        migrations.AddField(
            model_name='historicalspacetimevolume',
            name='territory',
            field=django.contrib.gis.db.models.fields.GeometryField(default=django.contrib.gis.geos.Polygon(((3, 3), (3, 4), (4, 4), (3, 3))), srid=4326),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='spacetimevolume',
            name='territory',
        ),
        migrations.AddField(
            model_name='spacetimevolume',
            name='territory',
            field=django.contrib.gis.db.models.fields.GeometryField(default=django.contrib.gis.geos.Polygon(((3, 3), (3, 4), (4, 4), (3, 3))), srid=4326),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AtomicPolygon',
        ),
        migrations.DeleteModel(
            name='HistoricalAtomicPolygon',
        ),
    ]
