# Generated by Django 2.1.5 on 2019-01-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190126_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacetimevolume',
            name='related_events',
            field=models.ManyToManyField(blank=True, to='api.CachedData'),
        ),
    ]
