# Generated by Django 2.1.2 on 2018-11-22 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181122_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRelation',
            fields=[
                ('politicalrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.PoliticalRelation')),
                ('relation_type', models.PositiveIntegerField()),
                ('children', models.ManyToManyField(related_name='parent_relation', to='api.PoliticalEntity')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='api.PoliticalEntity')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.politicalrelation',),
        ),
    ]
