# Generated by Django 2.1.2 on 2018-11-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_grouprelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicalentity',
            name='id',
        ),
        migrations.AlterField(
            model_name='politicalentity',
            name='wikidata_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
