# Generated by Django 2.1.5 on 2019-01-27 18:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190126_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnarration',
            name='date_label',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalnarrative',
            name='author',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalnarrative',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='narration',
            name='date_label',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='author',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), size=None),
        ),
    ]
