# Generated by Django 2.2 on 2019-04-29 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20190418_1106'),
        ('api', '0009_auto_20190421_0440'),
    ]

    operations = [
    ]
