# Generated by Django 2.2 on 2019-04-30 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190421_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacetimevolume',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stvs', to='api.TerritorialEntity'),
        ),
    ]
