# Generated by Django 2.1.5 on 2019-01-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190127_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narration',
            name='attached_events',
            field=models.ManyToManyField(blank=True, to='api.CachedData'),
        ),
    ]
