# Generated by Django 2.2 on 2019-05-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190430_0334'),
        ('api', '0010_merge_20190429_2346'),
    ]

    operations = [
    ]
