# Generated by Django 2.2.1 on 2019-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190430_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalterritorialentity',
            name='dissolution_date',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalterritorialentity',
            name='inception_date',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='territorialentity',
            name='dissolution_date',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='territorialentity',
            name='inception_date',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
