# Generated by Django 2.2.1 on 2019-05-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190511_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalterritorialentity',
            name='label',
            field=models.TextField(default='default', max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='territorialentity',
            name='label',
            field=models.TextField(default='default', max_length=90),
            preserve_default=False,
        ),
    ]
