# Generated by Django 2.2.1 on 2019-05-18 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_merge_20190506_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='votes',
        ),
        migrations.AddField(
            model_name='narrative',
            name='votes',
            field=models.ManyToManyField(related_name='narrative_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NarrativeVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField()),
                ('narrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Narrative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
