# Generated by Django 2.1.5 on 2019-02-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190127_2143'),
        ('api', '0008_auto_20190129_1408'),
    ]

    operations = [
    ]
