# Generated by Django 2.2 on 2019-05-22 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_auto_20190522_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrativevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='narrativevote',
            unique_together={('narrative', 'user')},
        ),
    ]
