# Generated by Django 2.2.1 on 2019-05-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190511_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorialentity',
            name='predecessor',
            field=models.ManyToManyField(blank=True, to='api.TerritorialEntity'),
        ),
        migrations.AlterField(
            model_name='historicalterritorialentity',
            name='dissolution_date',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalterritorialentity',
            name='inception_date',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='territorialentity',
            name='dissolution_date',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='territorialentity',
            name='inception_date',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
