# Generated by Django 2.1.5 on 2019-02-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20190206_1106'),
        ('api', '0009_merge_20190207_0037'),
    ]

    operations = [
    ]
