# Generated by Django 2.2.1 on 2019-06-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190608_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalterritorialentity',
            name='stv_count',
        ),
        migrations.RemoveField(
            model_name='territorialentity',
            name='stv_count',
        ),
        migrations.AlterField(
            model_name='historicalterritorialentity',
            name='inception_date',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='territorialentity',
            name='inception_date',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
