# Generated by Django 2.1.5 on 2019-02-09 01:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20190208_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheddata',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='historicalcacheddata',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
