# Generated by Django 2.1.5 on 2019-02-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20190208_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnarrative',
            name='url',
            field=models.TextField(db_index=True, default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='narrative',
            name='url',
            field=models.TextField(default='test', unique=True),
            preserve_default=False,
        ),
    ]
