# Generated by Django 2.1.5 on 2019-02-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20190208_0428'),
        ('api', '0013_merge_20190208_0424'),
    ]

    operations = [
    ]
