# Generated by Django 2.1.5 on 2019-02-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20190208_0424'),
        ('api', '0008_auto_20190208_1552'),
    ]

    operations = [
    ]
