# Generated by Django 2.1.5 on 2019-02-08 18:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20190208_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspacetimevolume',
            name='visual_center',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='spacetimevolume',
            name='visual_center',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
