# Generated by Django 2.1.5 on 2019-02-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190209_2226'),
        ('api', '0014_auto_20190209_0147'),
    ]

    operations = [
    ]
