# Generated by Django 2.2.2 on 2019-06-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190613_0622'),
        ('api', '0013_auto_20190522_1108'),
    ]

    operations = [
    ]
