# Generated by Django 2.1.5 on 2019-02-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20190209_2303'),
        ('api', '0014_merge_20190209_2217'),
    ]

    operations = [
    ]
