# Generated by Django 2.2.4 on 2019-08-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_symbol_narration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbol',
            old_name='narration',
            new_name='narrations',
        ),
    ]
