# Generated by Django 2.2.7 on 2020-01-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191223_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalterritorialentity',
            name='color',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='territorialentity',
            name='color',
            field=models.TextField(max_length=20),
        ),
    ]
