# Generated by Django 2.2.10 on 2020-02-10 23:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191223_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspacetimevolume',
            name='references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='spacetimevolume',
            name='references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), blank=True, null=True, size=None),
        ),
    ]
