# Generated by Django 2.2.9 on 2020-02-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200210_2309'),
        ('api', '0020_auto_20200131_1556'),
    ]

    operations = [
    ]
