# Generated by Django 2.2.9 on 2020-03-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20200213_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspacetimevolume',
            name='group',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
