# Generated by Django 2.2.10 on 2020-03-12 18:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20200213_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom', models.PositiveIntegerField()),
                ('x_coor', models.PositiveIntegerField()),
                ('y_coor', models.PositiveIntegerField()),
                ('bbox', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'unique_together': {('zoom', 'x_coor', 'y_coor')},
            },
        ),
        migrations.CreateModel(
            name='MVTLayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom', models.PositiveIntegerField()),
                ('x_coor', models.PositiveIntegerField()),
                ('y_coor', models.PositiveIntegerField()),
                ('layer', models.TextField(max_length=64)),
                ('tile', models.BinaryField()),
            ],
            options={
                'unique_together': {('zoom', 'x_coor', 'y_coor', 'layer')},
            },
        ),
    ]
