# Generated by Django 2.2.9 on 2020-03-14 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20200213_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspacetimevolume',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='api.SpacetimeVolume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalterritorialentity',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, default=9, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='api.TerritorialEntity'),
            preserve_default=False,
        ),
    ]
