# Generated by Django 2.2.9 on 2020-03-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_historicalspacetimevolume_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspacetimevolume',
            name='group',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
