# Generated by Django 4.1.5 on 2023-01-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_mapcolorscheme"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcacheddata",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical cached data",
                "verbose_name_plural": "historical cached datas",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcity",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical city",
                "verbose_name_plural": "historical citys",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmapsettings",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical map settings",
                "verbose_name_plural": "historical map settingss",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalnarration",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical narration",
                "verbose_name_plural": "historical narrations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalnarrative",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical narrative",
                "verbose_name_plural": "historical narratives",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpoliticalrelation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical political relation",
                "verbose_name_plural": "historical political relations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalspacetimevolume",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical spacetime volume",
                "verbose_name_plural": "historical spacetime volumes",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsymbol",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical symbol",
                "verbose_name_plural": "historical symbols",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalterritorialentity",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical territorial entity",
                "verbose_name_plural": "historical territorial entitys",
            },
        ),
        migrations.AlterField(
            model_name="historicalcacheddata",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcity",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmapsettings",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalnarration",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalnarrative",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpoliticalrelation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalspacetimevolume",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalsymbol",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalterritorialentity",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
