# Generated by Django 2.2.11 on 2020-03-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200315_0628'),
        ('api', '0023_mapcolorscheme'),
    ]

    operations = [
    ]
