FROM chronmaps/backend:deps-build as build
# chronmaps/backend:deps-python

RUN pip install "poetry==$POETRY_VERSION" 

WORKDIR $PYSETUP_PATH
COPY pyproject.toml poetry.lock ./
RUN poetry install

ENTRYPOINT /bin/sh
