name: System Image
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # build
      - uses: actions/checkout@v3
      - run: >
          mv django.env.sample django.env &&
          mv postgres.env.sample postgres.env &&
          mv mbtiles.env.sample mbtiles.env &&
          touch auth.env
      - env:
          SERVICE_KEY_BASE64: ${{ secrets.SERVICE_KEY_BASE64 }}
        run: echo "${SERVICE_KEY_BASE64// /}" | base64 --decode > config/firebase.json
      - run: make system-image
      # deploy
      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker push
        run: make push-system
